/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-Compact-Encoding-Detection.h
 #	source generated by 4D Plugin Wizard
 #	Project : Compact Encoding Detection
 #	author : miyako
 #	2020/01/14
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_COMPACT_ENCODING_DETECTION_H
#define PLUGIN_COMPACT_ENCODING_DETECTION_H

#include "4DPluginAPI.h"
#include "compact_enc_det/compact_enc_det.h"
#include "4DPlugin-JSON.h"
#include <vector>

#pragma mark -

void CED_Detect_encoding(PA_PluginParameters params);

#endif /* PLUGIN_COMPACT_ENCODING_DETECTION_H */
